name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - stage
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    if: contains('refs/heads/dev refs/heads/stage refs/heads/prod', github.ref)
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build
        run: echo "Building for branch ${{ github.ref_name }}"

  test:
    runs-on: ubuntu-latest
    needs: build
    if: contains('refs/heads/dev refs/heads/stage refs/heads/prod', github.ref)
    steps:
      - name: Test
        run: echo "Testing for branch ${{ github.ref_name }}"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: contains('refs/heads/dev refs/heads/stage refs/heads/prod', github.ref)
    steps:
      - name: Deploy
        run: echo "Deploying for branch ${{ github.ref_name }}"
